#!/bin/bash

mv anatomy-ac ac
chmod +x ac/anatomy ac/install

for item in index settings; do
	ac/anatomy model $item
	cp ac/library/$item.php $item.php
done

mkdir assets
mkdir assets/css && touch assets/css/.gitkeep
mkdir assets/img && touch assets/img/.gitkeep
mkdir assets/js && touch assets/js/client.js

mkdir embed/client
touch embed/client/funcs.html
touch embed/client/vars.html
mkdir embed/client/layout
for item in footer head header; do
	touch embed/client/layout/$item.html
	echo "<cms:extends 'anatomy/layout/$item.html' />" >> embed/client/layout/$item.html
done

git clone https://github.com/goanatomic/anatomy.git
git clone https://github.com/goanatomic/anatomy-couch.git
git clone https://github.com/goanatomic/anatomy-filters.git
git clone https://github.com/goanatomic/anatomy-vendor.git

mkdir embed
mv anatomy embed/anatomy
mv anatomy-couch admin
mv anatomy-filters embed/filters
mv anatomy-vendor vendor