#!/bin/bash
function createModel() {
	if [ -d embed/templates/$1 ]; then
		echo "Model already exists . . ."
	else
		mkdir -p embed/templates/$1
		mkdir -p embed/templates/$1/views && touch embed/templates/$1/routes.html
		for view in list create show edit delete; do
			echo "<cms:extends 'anatomy/root.html' />" >> embed/templates/$1/views/$view.html
		done
		touch embed/templates/$1/$1.css
		touch embed/templates/$1/$1.js
		touch ./$1.php
		echo "<?php require_once('admin/cms.php');?>" >> ./$1.php
		echo "<cms:extends 'anatomy/template.html' />" >> ./$1.php
		echo "" >> ./$1.php
		echo "<cms:block 'set-template'>" >> ./$1.php
		echo -e "\t<cms:call 'template'" >> ./$1.php
		echo -e "\t\t" >> ./$1.php
		echo -e "\t/>" >> ./$1.php
		echo "</cms:block>" >> ./$1.php
		echo "" >> ./$1.php
		echo "<?php COUCH::invoke( K_IGNORE_CONTEXT ); ?>" >> ./$1.php
	fi
}

createModel $1
sublime $1.php