#!/bin/bash
. "ac/config.sh"

if [ $# -eq 0 ]; then
	root=pwd
	# new comment
	git submodule foreach 'git pull origin master'
elif [ $1 = 'status' ]; then
	echo -e '\nStill working on an update option. Check back later.\n'
fi